openapi: 3.0.0
info:
  version: 1.0.0
  title: WizCloud Authentication
  description: ensure authentication
servers:
  - url: https://lb1.wizcloud.co.il
paths:
  /createSession/{wizKey}/{company}:
    get:
      description: Returns a Token
      parameters:
        - in: path
          name: wizKey
          required: true
          schema:
            $ref: '#components/parameters/wizKey'
          description: The user ID
        - in: path
          name: company
          required: true
          schema:
            $ref: "#components/parameters/company"
      responses:
        "200":
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example: "e923e7123e6c3d976c16cd667dfb346tf4d3df11365eb08e93c663dd6f02dfd424g8465ecc27da556bba10944fbdb33ed436ud62d8da7566a405369840bac23d222266b1fcc9b5114331530e5d1c215fd0b3e37a16ecb9fda7e357796c39b65bb0d320e05138ae280ead60faaf9df08e"
        "400":
          description: iligal gmail
          content:
            text/plain:
              schema:
                type: string
components:
  parameters:
    wizKey:
      name: wiz_key
      in: path
      description: copied from apiPermits.html
      required: true
      schema:
        type: string
    company:
      name: company
      in: path
      description: copied from apiPermits.html
      required: true
      schema:
        type: string